window.DEMO_DATA = {
  user: {
    id: "demo-user-ui",
    email: "22521738@gm.uit.edu.vn",
  },
  profile: {
    full_name: "Tran Thao",
    mssv: "22521738",
    is_verified: true,
    bio: "Sinh vien K22 yeu thich hoc nhom, thich giai tich va lap trinh.",
    avatar_url: "https://api.dicebear.com/7.x/thumbs/svg?seed=TranThao&backgroundColor=1f5f8b",
  },
  cards: [
    {
      id: 101,
      user_id: "demo-user-ui",
      type: "study",
      subject: "Giải tích",
      method: "offline",
      location_or_link: "Thư viện UIT",
      time: "Thứ 4, 18:30 - 20:30",
      slots: 5,
      current_slots: 3,
      note: "Ôn chương tích phân và ứng dụng. Ưu tiên các bạn K20.",
      profiles: {
        full_name: "Tran Thao",
        mssv: "22521738",
        is_verified: true,
        avatar_url: "https://api.dicebear.com/7.x/thumbs/svg?seed=TranThao&backgroundColor=1f5f8b",
      },
    },
    {
      id: 102,
      user_id: "demo-user-2",
      type: "study",
      subject: "Cấu trúc dữ liệu và giải thuật",
      method: "online",
      location_or_link: "https://meet.google.com/demo-dsa",
      time: "Chủ nhật, 09:00 - 11:00",
      slots: 4,
      current_slots: 2,
      note: "Giải bài tập list, stack, queue và đệ quy.",
      profiles: {
        full_name: "Nguyen Minh",
        mssv: "23520045",
        is_verified: true,
        avatar_url: "https://api.dicebear.com/7.x/thumbs/svg?seed=NguyenMinh&backgroundColor=2d8dbd",
      },
    },
    {
      id: 201,
      user_id: "demo-user-3",
      type: "tutor",
      subject: "Lập trình C++",
      method: "offline",
      location_or_link: "Phòng C205, UIT",
      time: "Thu 6, 14:00 - 16:00",
      slots: 3,
      current_slots: 1,
      note: "Hướng dẫn con trỏ, struct, file va OOP cơ bản.",
      tutor_role: "offering",
      profiles: {
        full_name: "Le Hoang Anh",
        mssv: "21520111",
        is_verified: true,
        avatar_url: "https://api.dicebear.com/7.x/thumbs/svg?seed=LeHoangAnh&backgroundColor=138a5d",
      },
    },
    {
      id: 202,
      user_id: "demo-user-4",
      type: "tutor",
      subject: "Cơ sở dữ liệu",
      method: "online",
      location_or_link: "https://meet.google.com/demo-db",
      time: "Thu 7, 19:00 - 21:00",
      slots: 6,
      current_slots: 4,
      note: "Cần gia sư hỗ trợ ERD, chuyển đổi bảng và SQL query.",
      tutor_role: "seeking",
      profiles: {
        full_name: "Pham Gia Bao",
        mssv: "24521234",
        is_verified: false,
        avatar_url: "https://api.dicebear.com/7.x/thumbs/svg?seed=PhamGiaBao&backgroundColor=c7791a",
      },
    },
  ],
  conversations: [
    {
      id: "demo-user-2",
      name: "Nguyen Minh",
      mssv: "23520045",
      last: "Toi gui tai lieu cho ban roi nhe.",
      lastTime: "2026-03-27T14:15:00",
      messages: [
        {
          mine: false,
          text: "Toi co group on DSA toi Chu nhat, ban tham gia khong?",
          time: "14:05",
          createdAt: "2026-03-27T14:05:00",
        },
        {
          mine: true,
          text: "Co nhe, gui minh link voi.",
          time: "14:08",
          createdAt: "2026-03-27T14:08:00",
        },
        {
          mine: false,
          text: "Toi gui tai lieu cho ban roi nhe.",
          time: "14:15",
          createdAt: "2026-03-27T14:15:00",
        },
      ],
    },
  ],
};
